### PR TITLE
Java: include debug information with compiled code

### LINKED ISSUE #32: Java: Include debug information with compiled code by default
Currently, the java libraries are compiled without debug information which makes it impossible for the consumer of the library to debug in case of error. 

To include debug information, update the build.xml and set the property compile.debug to true

```
<property name="compile.debug"       value="true"/>
```

### PR DESCRIPTION
**Pull request by vuongddang**
resolves #32,  update build.xml set compile.debug property to true
To include debug information with compiled code

### CODE REVIEW

**Comment by tbouffard** [comment]
I am not sure if we can accept pull request targeting the main branch. There is a limitation due to the current license hold in the main branch that has been included after the 4.2.2 release and just before the original mxgraph EOL, see https://github.com/jgraph/mxgraph/issues/505
I addition, we may remove the java support from this repo, see https://github.com/jsGraph/mxgraph/issues/32#issuecomment-833406403

**Comment by vuongddang** [comment]
I understand. Just a question on the license, I see that the latest license is also in the development branch, does that mean the limitation you mentioned also applies to the development branch?

**Comment by tbouffard** [comment]
I guess that for now, yes we have the license limitation.
I didn't have time to open a [discussion](https://github.com/jsGraph/mxgraph/discussions) to talk with the other contributors about this topic, but this is something we have to clarify as soon as as possible.

**Comment by Kurt29** [comment]
Wow, that license change looks bad. It would be great if it is solvable, otherwise we might never be able to change to this project and might need to downgrade our used mxgraph version

**Comment by tbouffard** [comment]
The license change has been introduced after the mxgraph 4.2.2 release and soon before the original implementation reach end of life.
All code released prior the license change is still covered by the default/regular Apache-2.0 license without the modified clause 4e of Apache 2 license (with restricts works targetting Atlassian's Jira or Confluence products). And I guess that we don't want to keep this restriction with the initiative in progress in the new repository.

**Pull request closed without merging**
