### PR TITLE
fix: allow `HierarchicalLayout` to manage circular dependencies

### LINKED ISSUE #231: Getting error on circular dependency using HierarchicalLayout
Hi, 
I try to migrate the mxGraph library to the maxGraph library in my project, and receive an error on a use case which used to work on the old mxGraph library.

When I try to create a HierarchicalLayout which contains a circular dependency, I receive an error:

TypeError: Cannot read properties of undefined (reading 'push')
    at http://localhost:8901/main.iframe.bundle.js:69642:34
    at GraphHierarchyModel.dfs (http://localhost:8901/main.iframe.bundle.js:69729:11)
    at GraphHierarchyModel.dfs (http://localhost:8901/main.iframe.bundle.js:69738:18)
    at GraphHierarchyModel.visit (http://localhost:8901/main.iframe.bundle.js:69700:20)
    at GraphHierarchyModel.fixRanks (http://localhost:8901/main.iframe.bundle.js:69640:12)
    at HierarchicalLayout.layeringStage (http://localhost:8901/main.iframe.bundle.js:62750:13)
    at HierarchicalLayout.run (http://localhost:8901/main.iframe.bundle.js:62543:14)
    at http://localhost:8901/main.iframe.bundle.js:62281:16
    at GraphDataModel.batchUpdate (http://localhost:8901/main.iframe.bundle.js:20316:9)
    at HierarchicalLayout.execute (http://localhost:8901/main.iframe.bundle.js:62280:13)
    
 
Let me provide you a simple setup scenario, which is based on the example in packages\html\stories\HierarchicalLayout.stories.js:

    const v1 = graph.insertVertex(parent, null, '1', 0, 0, 80, 30);
    const v2 = graph.insertVertex(parent, null, '2', 0, 0, 80, 30);
    const v3 = graph.insertVertex(parent, null, '3', 0, 0, 80, 30);
    const v4 = graph.insertVertex(parent, null, '4', 0, 0, 80, 30);
    const v5 = graph.insertVertex(parent, null, '5', 0, 0, 80, 30);
    const v6 = graph.insertVertex(parent, null, '6', 0, 0, 80, 30);
    const v7 = graph.insertVertex(parent, null, '7', 0, 0, 80, 30);
    const v8 = graph.insertVertex(parent, null, '8', 0, 0, 80, 30);
    const v9 = graph.insertVertex(parent, null, '9', 0, 0, 80, 30);

    const e1 = graph.insertEdge(parent, null, '', v1, v2);
    const e2 = graph.insertEdge(parent, null, '', v2, v3);
    const e3 = graph.insertEdge(parent, null, '', v3, v4);
    const e4 = graph.insertEdge(parent, null, '', v4, v5);
    const e5 = graph.insertEdge(parent, null, '', v5, v3);
    const e6 = graph.insertEdge(parent, null, '', v5, v6);
    const e7 = graph.insertEdge(parent, null, '', v6, v7);
    const e8 = graph.insertEdge(parent, null, '', v7, v8);
    const e9 = graph.insertEdge(parent, null, '', v8, v9);
    
Running the HierarchicalLayout#execute() method results in the exception above.
I was already able to identify, that the rankList which is created on the startup seems not to identify the correct layer depth, which end at layer 3. However, I was expecting the same behaviour as in the legacy code: https://github.com/jgraph/mxgraph/blob/master/javascript/src/js/layout/hierarchical/mxHierarchicalLayout.js. , which I can confirm can render a hierarchical graph with the same edge configuration as above.

Can some one confirm, that this is a bug?

### PR DESCRIPTION
**Pull request by Franz-Ritter**
**Summary**
Solved bug creating a graph with a circular dependency using the HiearchlLayout.ts algorithm.

Check this [issue ](https://github.com/maxGraph/maxGraph/issues/231) for more detailed information including an example to reproduce the bug

**Solution:**

Uncomment the isAncestor method GraphHierachyNode, which is used by HiearchlLayout. The uncommented implementation makes sure, that a circular dependency is detected and resolved. Using the default isAncestor does not work at this point, because the parent nodes of the child nodes in the graph are not set.

Closes #231

### CODE REVIEW

**Comment by tbouffard** [comment]
Hi @Franz-Ritter did you try to add automatic tests as I suggested in the issue?

This would reproduce the initial problem and show that is now fixed.

**Comment by Franz-Ritter** [comment]
Hi @tbouffard, Sorry I oversaw your comment. I try to find time to check how you structure your tests, and add one to the PR as requested.

**Comment by Franz-Ritter** [comment]
@tbouffard I added a test which creates a cyclic Graph and a non-cyclic graph.
Please consider that I am not a native typescript developer...
Anyway, both graph used to work using mxGraph. When you do and checkout the code and execute the test without the change in `GraphHierarchyNode` one of the tests fails. However, my change let both test pass.

If you have any questions or need more input, please let me know. Applying that fix on the code base would help me a lot. Atm i am forced to package and link the change locally.

**Comment by Franz-Ritter** [comment]
@tbouffard Do you need some additional input?

**Comment by tbouffard** [comment]
Hi @Franz-Ritter 
I have been busy at work and I haven't had time to have a look at this Pull Request.
I will check it in a few days.

**Review by tbouffard — APPROVED** [review]
@Franz-Ritter It's all good to me. Thanks
- ✔️ reproduce the issue with newly introduced tests (prior the fix is applied)
- ℹ️ I push directly some lint fixes in the branch of this PR

**Pull request merged**
