### PR TITLE
fix: add null check to connection validation message

### LINKED ISSUE #362: The performance of the getCell method of the CollectionHandler class is different from that of the old version after migration.
### In maxGraph0.8., When ` this.connectionHandler.error `equals empty string，`this.connectionHandler.error && this.connectionHandler.error.length === 0`equals `false`
image

###  But in the old version, the value of this expression（`this.error != null && this.error.length == 0`） was `true`

image
### This is the result of the expression running on the console，the result is `true`
image
### I made a fix in my project to keep the original functionality. If Return values for `validateConnection ` is an empty string, I will use an empty array instead.
this.graph.getPlugin('ConnectionHandler').validateConnection = function(source, target) {
    let error = null;
    if (!this.isValidTarget(target)) {
        error = '';
    }
    error = this.graph.getEdgeValidationError(null, source, target);
    return error === '' ? [] : error;
}

### PR DESCRIPTION
**Pull request by eRedekopp**
**Summary**
If-statement in ConnectionHandlerCellMarker was looking for `this.connectionHandler.error` to be an empty string, but used check `this.connectionHandler.error && this.connectionHandler.error.length === 0`, which is false when the string is empty because `""` is falsy. Reverted to the syntax used in mxgraph. This was noticed by issue #362

**Description for the changelog**
Add null check to connection validation message in ConnectionHandlerCellMarker to handler invalid connection targets.

Closes #362

### CODE REVIEW

**Comment by eRedekopp** [comment]
This specifically needs to check for an empty string because `validateConnection` returns an empty string to indicate that the connection target was invalid. Do you think it might make more sense to indicate this in a more robust way, like maybe returning a specific message indicating that? For example, what if `getEdgeValidationErrors` returns an empty string as an error message -- is that something we need to worry about?

**Comment by tbouffard** [comment]
Sorry for the late answer, I don't have time to review this PR for now.
I need some time to figure out what is the context. I hope to come back to you soon with insights.

**Comment by tbouffard** [comment]
Apparently, the Validation story reproduces the original problem (see #73), so it should work with this fix.

**Review by tbouffard — APPROVED** [review]
I have not been able to reproduce the problem with the Validation story. The null check in `Multiplicity.checkTerminal` remove errors in the Story.
As the proposed fix restores the mxGraph implementation, this is OK for now. Improvements of the error management can be done later.

Notice that the Validation story shows that the error message are not correctly display. A "key" is used instead of the actual error message. Fixing this problem was out of the scope of this PR.

Here is how the Validation story behaves with this PR 👇🏿 

PR_364_Validation_story

**Pull request merged**
