### PR TITLE
Apply eslint and prettier autofixes on codebase

### PR DESCRIPTION
**Pull request by mayorovad**
**Summary**

Theme of this PR is #122. I will try to not create huge PRs on this issue in future, but this one is really big, because auto-scripts applied. I didn't change any code manually.

- Add missing `eslint` deps in package.json
- Run `lint:fix` and `prettier` scripts

**Description for the changelog**
- Refactor code based on eslint and prettier rules

**Other info**
Not so sure about eslint rule that eliminates type declarations for variables with defined values 🤔. If it's not ok for you, I can revert it back.

### CODE REVIEW

**Comment by Kurt29** [comment]
I like that you don't have to add type declarations for inferred default values. And as long as there is no huge other PR right now, it shouldn't be an issue that this branch is a little bigger than usual

**Comment by tbouffard** [comment]
Sorry for the late answer
I agree with @Kurt29 there are no large PRs, and existing ones have been created by @mayorovad 😸 so we will eventually fix the lint errors in the opened PR afterwards.
I should be able to review this PR soon

**Review by tbouffard — CHANGES_REQUESTED** [review]
⚠️ I  see a lot of remaining errors (confirm when running with GitHub Actions). I suggest we fix them now otherwise new ones will be included in the future.
These errors are not not auto-fixed by eslint so I guess that's why they remain

**Review by tbouffard — APPROVED** [review]
LGTM, thanks @mayorovad for having fixed all eslint errors 👍🏿

**Pull request merged**
