### PR TITLE
fix(docs) Update default value for mxForceIncludes variable

### PR DESCRIPTION
**Pull request by holyhope**
Signed-off-by: Pierre Péronnet <pierre.peronnet@ovhcloud.com>

### CODE REVIEW

**Review by jgadsden — CHANGES_REQUESTED** [review]
Hello @holyhope - could you provide the reason for this change please? Also is there an issue that it addresses?

No problem with the change itself, just needed to know the reasoning

**Comment by holyhope** [comment]
Hello @jgadsden ,

Thank you for the reply.

Of course you are right, moreover on github reviews, only few context lines are shown.

This changes is a fix probably due to a bad copy/past:
The comment does not match the variable.
So I updated the variable name as well as the default value to match the real value fee line later.

**Comment by tbouffard** [comment]
We currently cannot accept Pull Request targetting the `main` branch due to a license issue and we need to clarify it first IMHO. See #35.
That being said, the `mxForceIncludes` documentation is out-of-sync with the code (unfortunately, this is something that is present in a lot of mxGraph API documentation), so the content of this Pull Request is valid.

Regarding the `mxForceIncludes` global, I hope we will remove it in the `development` branch: this was a poor way used by the project to test the changes while developing. In addition, it is one of the property that wasn't set correctly while initializing mxGraph when using the npm package (https://github.com/jgraph/mxgraph/issues/479) and also caused issue when using in TypeScript project (https://github.com/typed-mxgraph/typed-mxgraph-example-bundled-with-rollup/blob/f576c1bfeb7a45488cfa8c613f94517a4003477d/src/mxgraph-loader.ts#L10)

**Comment by jgadsden** [comment]
I agree @tbouffard that we need to use development branch for the time being. This caught me out as well @holyhope and I have changed my two pull requests to be for development rather than main.

@holyhope could you recreate your proposed changes against development branch, taking into account @tbouffard comments? And then close (without merging) this pull request

Thanks, Jon

**Pull request closed without merging**
