### PR TITLE
Made calls go directly to mxCell rather than through mxGraphModel in many cases

### PR DESCRIPTION
**Pull request by mcyph**
In this PR I've made it so most calls in the examples and core go directly to `mxCell` rather than going through `mxGraphModel` to improve readability+simplicity for newer users. The previous functions in `mxGraphModel` are still there but now forward to the `mxCell` function with a `// SLATED FOR DELETION` comment to indicate it may be removed at a later date.

So for example:

```javascript
if (!state.view.graph.getModel().isEdge(state.cell)) {
```

will become

```javascript
if (!state.cell.isEdge()) {
```

I also have started to remove some of the `null`s as possible types to functions in `mxCell` to try to eliminate bugs which occur due to `null`s being accidentally passed to functions and no exception raised, but please note this also will introduce bugs in some cases, especially where `null` is passed from non-typescript/plain-js files which don't have as strict checking.

### CODE REVIEW

**Comment by junsikshim** [comment]
What are those `docs/stashed/*` files?
They look like examples, but are in a weird location...

**Comment by mcyph** [comment]
> What are those `docs/stashed/*` files?
> They look like examples, but are in a weird location...

Yeah, they are the examples I didn't convert/started converting to react but hadn't yet finished. I put them there outside the source code tree because React/next.js wouldn't work unless all the javascript files were parseable.

Those "stashed" examples were still there prior to this PR, and mainly only things related to `mxGraphModel` should have been changed this time around in that dir.
Some of these were relatively complex examples or depended on other things working first, and was leaving refactoring/converting the examples till later. This includes the "editor" examples you can view at https://jgraph.github.io/mxgraph/javascript/.

**Comment by mcyph** [comment]
I wonder how the big "Editor" code differs in scope and whether it was derived from/turned into https://draw.io ?

I'm wondering whether it may be worth investigating whether https://github.com/jgraph/drawio itself could be converted to ES9 and added to the library/put into an external package if it's not orders of magnitude larger.

**Comment by junsikshim** [comment]
> Those "stashed" examples were still there prior to this PR

Oh, I just realized I had `docs` excluded in my vscode config.
I never saw them until now. lol

Btw, I'm still converting your examples(the ones in `src/pages/`) into storybook. I'll open a PR when it's ready.

**Review by junsikshim — APPROVED** [review]

**Pull request merged**
