### PR TITLE
feat: restore remaining non-"Editor" examples to Storybook

### PR DESCRIPTION
**Pull request by mcyph**
**Summary**

Converted the following remaining "stashed" examples to StoryBook:

* Wires
* GraphLayout
* ShowRegion
* MenuStyle
* HtmlLabel
* ShowRegion

Mostly have finished converting, but issues still remain:

* Scrollbars (is starting to display, but appears to have a bug where `<g>` elements are inserted outside of the `<svg>` element)
* Codec (does not appear to load elements; needs to be investigated) 

This is in addition to the PR at https://github.com/maxGraph/maxGraph/pull/149 which converted the "Pinch Zoom" example. Editor examples still remain unconverted, although some progress has been made converting the "Ports" example to StoryBook.

Also has some fixes for the default parameters for `MaxPopupMenu` to restore the original mxGraph behavior.

**Description for the changelog**

Converted remaining "stashed" non-Editor and touch-related examples to StoryBook.

**Other info**

[_UPDATE] The following has been reverted, see https://github.com/maxGraph/maxGraph/pull/150#issuecomment-1342096040, #151 and 43ab435._
This adds an additional parameter to the main `Graph` class to allow overriding the class constructors in the "instantiators" parameter. I think there may be a better term for this, and there is a good question whether this should be merged into the "plugins", or references to these class constructors set in the class variables and overridden in subclasses.

As in types.ts, the following are able to be overridden:

```typescript
export type GraphInstantiators = {
  GraphDataModel?: typeof GraphDataModel,
  GraphSelectionModel?: typeof GraphSelectionModel,
  Stylesheet?: typeof Stylesheet,
  GraphView?: typeof GraphView,
  CellRenderer?: typeof CellRenderer,
  VertexHandler?: typeof VertexHandler,
  EdgeHandler?: typeof EdgeHandler,
  EdgeSegmentHandler?: typeof EdgeSegmentHandler,
  ElbowEdgeHandler?: typeof ElbowEdgeHandler,
}
```

Still unresolved is how to allow "local" changes to style (color, size etc) variables in `Constants.ts` that are referred. I think it may make sense to allow providing these as an argument to `Graph`, or have some way of assigning these locally.

### CODE REVIEW

**Comment by tbouffard** [comment]
@mcyph I don't understand the need to introduce `GraphInstantiators`, at least today.

There are already ways to override the `Graph` defaults:
- `GraphModel`: pass it in the constructor
- others: subclass `Graph` and override the `createXXX` methods

This is the historical mxGraph way. We can change it but this needs more discussions IMHO. 
For instance (non exhaustive list)
- with the current proposal, we now have two ways to override the default implementation: Subclass and composition. Why not keeping only one way for simplicity?
- If we remove the `createXX` methods, this will introduce more API breaks comparing to mxGraph

There are pros and cons for all solutions.
So I suggest to not implement it in this Pull Request and create a dedicated discussion to collectively choose what we want.

Does it make sense?

**Comment by mcyph** [comment]
@tbouffard I will open a new pull request, but I believe the fundamental problem is the way certain methods in the original Graph class instantiate hardcoded references to those classes, in particular in the middle of reasonably complex logic such as in `Graph.createEdgeHandler`. The original mxGraph prioritised inheritance over composition in many places, and it's made making changes which are not global tricky. 

I can't think of many substantially better ways of solving this issue. It may simply have been this could be worked around for those previous examples, but I ran into difficult decisions for these final ones.

The options as I see them are:

* Make changes globally (previously these examples made page-global changes by altering the prototypes)
* Provide alternative constructors to the subclass as attributes
* Provide the alternative constructors to the constructor of the Graph object, similar to this PR 

I will detail these more in detail in the discussion when I get some time.

**Comment by mcyph** [comment]
I've actually been leaning more towards `create*` factory functions at times, as that has been what's been used for some but not all constructor calls in mxGraph in the base `Graph` class, but wasn't sure whether should adopt this pattern or reuse the pattern used for the plugins argument.

I suspect the plugins argument is mainly there for tree-shaking purposes. If the `create*` factory functions would be preferred, I would be inclined to alter this PR to do this, as don't have strong preferences between these approaches.

**Comment by mcyph** [comment]
@tbouffard Have started a new discussion at https://github.com/maxGraph/maxGraph/discussions/151 and moved my comments there, let me know your thoughts

**Comment by mcyph** [comment]
As I mention there, if wanting to keep with the conventions previously established by mxGraph I'm inclined to go with the `create*` factory functions and override them in subclasses, and will make this change in this branch in the interim.

Bear in mind the "draft" status of this merge request - I'm heading overseas for a few weeks+knew I likely won't have time to work on it while away, but have tried to fix as many examples as I could in last few weeks. I would've liked to have fixed the editor examples too, but I thought that would take longer. 

If anyone would like to make changes to this or the other "Touches" branch in the meantime feel free.

**Comment by tbouffard** [comment]
Thanks @mcyph for the quick feedback and the status. Don't worry, maxGraph already owes you a lot, so we can all wait a bit for the finalization of this contribution. 👍🏿 

I saw the Draft status, that's exactly why I wanted to let you know eventual issues with the newly introduced GraphInstantiators prior you move forward. 😄  I will feed the new discussion with my ideas.

**Comment by tbouffard** [comment]
About "_Codec (does not appear to load elements; needs to be investigated)_":
The XML in the "stashed Codec" example corresponds to the old mxGraph format, which is currently impossible to load with `maxGraph` until we implement #293. It is therefore not possible to load elements with the current XML content.
The XML content could be updated to use the `maxGraph` format and thus load the elements.

**Comment by tbouffard** [comment]
I am in the process of reviving this PR.
I'm testing the updated stories locally and if they work, I'll merge this PR.

**Comment by tbouffard** [comment]
I have made the following stories work with Storybook v7. They are still written in JavaScript (I didn't have time to port them to TypeScript):

- GraphLayout
- HtmlLabel
- MenuStyle
- ShowRegion
- Scrollbars
- Wires

The examples are still not fully working. As the mxGraph examples were previously migrated to nextjs/react, some original code may not have been ported correctly.

**Pull request merged**
